[profile.default]
src = "."
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true
ffi = true

# Remappings for Uniswap v4
remappings = [
    "v4-core/=lib/v4-core/",
    "v4-periphery/=lib/v4-periphery/",
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
]

[fuzz]
runs = 256
max_test_rejects = 65536

[invariant]
runs = 256
depth = 15

# See more config options at https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options